# Generated by Django 4.0.4 on 2022-09-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='materials_watchlist',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='schedule',
        ),
    ]
