# Generated by Django 4.0.4 on 2022-09-10 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_alter_userinfo_jobs_and_more'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user_info.userinfo'),
        ),
    ]
