# Generated by Django 4.0.4 on 2022-08-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jobs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='job.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='materials_watchlist',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='schedule',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
