# Generated by Django 4.0.4 on 2022-09-01 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('authentication', '0004_alter_user_jobs_alter_user_materials_watchlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.job'),
        ),
        migrations.AlterField(
            model_name='user',
            name='materials_watchlist',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='schedule',
            field=models.CharField(max_length=255),
        ),
    ]
