# Generated by Django 4.0.4 on 2022-08-27 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('materials', models.CharField(max_length=255)),
                ('estimate_price', models.CharField(max_length=255)),
                ('completion_status', models.BooleanField()),
                ('time_frame', models.CharField(max_length=255)),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photos.photo')),
            ],
        ),
    ]
