# Generated by Django 4.0.4 on 2022-09-10 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        ('job', '0002_alter_job_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='photos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='photos.photo'),
        ),
    ]
