# Generated by Django 4.0.4 on 2022-09-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='photos',
        ),
    ]
