# Generated by Django 4.0.4 on 2022-10-28 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=25)),
                ('materials_watchlist', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('photos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='photos.photo')),
            ],
        ),
    ]
