# Generated by Django 4.0.4 on 2022-09-06 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_photos'),
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='jobs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='job.job'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='materials_watchlist',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='schedule',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
