# Generated by Django 4.0.4 on 2022-09-10 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_photos'),
        ('user_info', '0002_alter_userinfo_jobs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='job.job'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='materials_watchlist',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='schedule',
            field=models.CharField(max_length=255),
        ),
    ]
