# Generated by Django 4.0.4 on 2022-09-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_userinfo_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='schedule',
            field=models.CharField(max_length=25),
        ),
    ]
