# Generated by Django 4.0.4 on 2022-09-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_remove_userinfo_phone_number_alter_userinfo_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
